version: 2
updates:
  # Enable version updates for nuget
  - package-ecosystem: "nuget"
    # Look for NuGet dependency info from the `root` directory
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
